---
- name: Reset database
  command: wp db reset --yes --allow-root
  args:
    chdir: "{{ www_root }}/{{ item.key }}/{{ item.value.current_path | default('current') }}/"
  with_dict: "{{ wordpress_sites }}"

- name: Import database
  command: wp db import dev-starter.sql --allow-root
  args:
    chdir: "{{ www_root }}/{{ item.key }}/{{ item.value.current_path | default('current') }}/"
  with_dict: "{{ wordpress_sites }}"

- name: Update bwm in database
  command: wp search-replace --recurse-objects --precise --all-tables --allow-root 'http:\/\/bwm.test' 'http:\/\/{{ site_env.wp_home }}'
  args:
    chdir: "{{ www_root }}/{{ item.key }}/{{ item.value.current_path | default('current') }}/"
  with_dict: "{{ wordpress_sites }}"

- name: Update admin
  command: wp user update brandworx 
            --user_pass="{{ vault_wordpress_sites[item.key].admin_password }}"
            --user_email="{{ item.value.admin_email }}"
            --allow-root
  args:
    chdir: "{{ www_root }}/{{ item.key }}/{{ item.value.current_path | default('current') }}/"
  with_dict: "{{ wordpress_sites }}"